# Generated by Django 6.0.1 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_points_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointledger',
            name='event',
            field=models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('adjusted', 'Adjusted'), ('purchased', 'Purchased')], max_length=20),
        ),
    ]
