# Generated by Django 6.0.1 on 2026-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_cbd_max_product_cbd_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('flower', 'Flower'), ('pre_roll', 'Pre-roll'), ('edible', 'Edible'), ('vape', 'Vape'), ('concentrate', 'Concentrate'), ('tincture', 'Tincture'), ('topical', 'Topical'), ('accessory', 'Accessory'), ('clothing', 'Clothing')], default='flower', max_length=20),
        ),
    ]
